### ISSUE TITLE
Rename `ImmutableObservable` to `Observable`

### ISSUE THREAD

**Issue by rharter** [roberthein/Observable#24]
The ImmutableObservable class is great, since it allows you to have a public API in your classes that is safe from external side effects, but the naming semantics are backwards.

The current name would imply that ImmutableObservable is a special kind of Observable that adds immutability, but that's not the case. Instead Observable is a special kind of ImmutableObservable that adds mutability, but that's not apparent from reading the names.

I addition, it litters your public API with extra information. The client shouldn't know or care that the Observable is immutable, that's an implementation detail that makes usages more verbose and less readable.

I suggest flipping the names, so the standard implementation is `Observable` and the subclass is `MutableObservable`. That would make the relationship clear and clean up public usages.

```swift
class SomeViewModel {
    /// Public property
    var position: Observable<CGPoint> = {
        return positionSubject
    }
    
    /// Private property
    private let positionSubject = MutableObservable(CGPoint.zero)
}
```

**Comment by 4brunu** [comment]
I agree! 
I think we can say that this is may fault, since I introduced those names...
The reason I introduce this naming was backwards compatibility, this way the `Observable` would keep it's previous behaviour.
One advantage of changing the `Observable` to be read only, it's that this it's closer to RxSwift that it's very popular, and a lot of people is familiar with, and it would be and easier entry level to this library.
The disadvantage is that, this would require some refactoring from the current users of the library.

**Comment by 4brunu** [comment]
I just created https://github.com/roberthein/Observable/pull/33 to try to fix this issue.

**Comment by 4brunu** [comment]
Since https://github.com/roberthein/Observable/pull/33 was merged, I think this issue can now be closed 🙂

**Comment by roberthein** [comment]
👌
